name = "MunusBackend"
uuid = "7f38fa8b-4cc3-4b7b-8a4a-79dd2c2f9456"
version = "0.1.0"

authors = ["Codex"]

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
